---
- name: clustering | /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip_address }} {{ item.node }}"
    state: present
    create: true
    mode: 0644
  with_items: "{{ elasticsearch_cluster_nodes }}"
  when: elasticsearch_populate_etc_hosts

- name: clustering | /etc/elasticsearch/elasticsearch.yml
  ansible.builtin.template:
    src: "{{ elasticsearch_elasticsearch_yml_template }}"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch
