---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- import_tasks: java.yml
  when: elasticsearch_jdk_install | bool

- name: Ensure needed packages are installed
  ansible.builtin.apt:
    name:
      - software-properties-common
      - curl
      - apt-transport-https
      - dirmngr
      - jq
      - zip  # for CVE-2021-44228
    state: present

- name: /etc/apt/trusted.gpg.d/elasticsearch.asc
  ansible.builtin.get_url:
    url: "{{ elasticsearch_gpg_url }}"
    dest: /etc/apt/trusted.gpg.d/elasticsearch.asc
    mode: '0440'

- name: Change ownership of a directory
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/elasticsearch.asc
    owner: _apt

- name: Elastic repository OSS
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/oss-{{ elasticsearch_version_depot }}/apt stable main
    state: present
    filename: elasticsearch
  when: elasticsearch_repo_origin == 'oss'

- name: Elastic repository ELASTIC
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/{{ elasticsearch_version_depot }}/apt stable main
    state: present
    filename: elasticsearch
  when: elasticsearch_repo_origin == 'elastic'

- name: Check if ElasticSearch already installed
  ansible.builtin.command: dpkg-query -W 'elasticsearch'
  no_log: true
  failed_when: false
  changed_when: false
  register: elasticsearch_is_installed

- name: show elasticsearch_is_installed
  ansible.builtin.debug:
    var: elasticsearch_is_installed.rc

- name: show elasticsearch_is_installed
  ansible.builtin.debug:
    var: elasticsearch_is_installed

- name: Mask ElasticSearch service
  ansible.builtin.systemd:
    name: elasticsearch
    masked: true
  when: elasticsearch_is_installed.rc != 1

- name: Install ElasticSearch
  ansible.builtin.apt:
    name: elasticsearch={{ elasticsearch_version }}
    state: present

# check CVE-2021-44228
- name: zip -q -d "…elasticsearch…/log4j-core-2.*.jar" 'org/apache/logging/log4j/core/lookup/JndiLookup.class'
  ansible.builtin.shell:
    cmd: |
      set -e -x
      # CVE-2021-44228 & CVE-2021-45046 impact log4j between version 2.0 and 2.15 (included)
      # log4j version: MAJOR.MINOR.PATCH
      JAR_PATH="$(dpkg -L elasticsearch | grep 'log4j-core-2.*\.jar$' || true)"

      # if MAJOR != 2 → everything is fine
      test -z "$JAR_PATH" && exit 0

      # get MINOR version
      JAR_MINOR_V="$(sed 's#^.*log4j-core-2\.\([^\.]*\)\..*\.jar$#\1#' <<< "$JAR_PATH")"

      # if MINOR >= 16 → everything is fine
      test "$JAR_MINOR_V" -ge 16 && exit 0

      if unzip -l "$JAR_PATH" | grep -q -F 'org/apache/logging/log4j/core/lookup/JndiLookup.class'
      then
        zip -q -d "$JAR_PATH" 'org/apache/logging/log4j/core/lookup/JndiLookup.class'
        echo "ANSIBLE CHANGED"
      fi
    executable: /bin/bash
  register: elasticsearch_cve_2021_44228_
  changed_when: elasticsearch_cve_2021_44228_.stdout.endswith('ANSIBLE CHANGED')
  notify:
    - restart elasticsearch

- name: /etc/default/elasticsearch
  ansible.builtin.template:
    src: default/elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch

- name: elasticsearch path data
  ansible.builtin.file:
    path: "{{ elasticsearch_path_data }}"
    owner: "{{ elasticsearch_default_user }}"
    group: "{{ elasticsearch_default_group }}"
    mode: 0750
    state: directory

- name: elasticsearch path logs
  ansible.builtin.file:
    path: "{{ elasticsearch_path_logs }}"
    owner: "{{ elasticsearch_default_user }}"
    group: "{{ elasticsearch_default_group }}"
    mode: 0750
    state: directory

- name: elasticsearch jna tmpdir
  ansible.builtin.file:
    path: "{{ elasticsearch_jna_tmpdir }}"
    owner: "{{ elasticsearch_default_user }}"
    group: "{{ elasticsearch_default_group }}"
    mode: 0750
    state: directory
  when: elasticsearch_jna_tmpdir not in ['/tmp', '/var/tmp']

- name: /etc/elasticsearch/elasticsearch.yml
  ansible.builtin.template:
    src: "{{ elasticsearch_elasticsearch_yml_template }}"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch

- name: /etc/elasticsearch/jvm.options
  ansible.builtin.template:
    src: "{{ elasticsearch_jvm_options_template }}"
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch

- name: /etc/elasticsearch/log4j2.properties
  ansible.builtin.template:
    src: "{{ elasticsearch_log4j2_properties_template }}"
    dest: /etc/elasticsearch/log4j2.properties
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch

- name: Create file /etc/systemd/system/elasticsearch.service.d/01-mlockall.conf
  ansible.builtin.template:
    src: systemd/system/elasticsearch.service.d/01-mlockall.conf
    dest: /etc/systemd/system/elasticsearch.service.d/
    owner: root
    group: root
    mode: 0444
  register: elasticsearch_mlock_systemd_file_
  notify:
    - restart elasticsearch
  when: elasticsearch_bootstrap_memory_lock

- name: Populate /etc/hosts
  when: not elasticsearch_cluster_setup and elasticsearch_populate_etc_hosts
  block:
    - name: getent
      ansible.builtin.getent:
        database: hosts
    - name: debug
      debug:
        var: getent_hosts
    - name: autre debug
      debug:
        var: elasticsearch_node_ip_address

    - name: change /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^{{ elasticsearch_node_ip_address }}\s'
        line: "{{ elasticsearch_node_ip_address }} {{ (getent_hosts[elasticsearch_node_ip_address] | default([])) | union([ansible_hostname]) | join(' ') }}"
        mode: 0644
        state: present
  tags: molecule-notest

- name: clustering tasks
  import_tasks: cluster.yml
  when: elasticsearch_cluster_setup | bool

- name: systemctl enable --now elasticsearch.service
  ansible.builtin.systemd:
    name: elasticsearch.service
    daemon-reload: "{{ elasticsearch_mlock_systemd_file_ is changed }}"
    masked: false
    enabled: true
    state: started

- name: plugins management
  import_tasks: plugins.yml

- name: templates management
  import_tasks: templates.yml
  when: elasticsearch_templates_enabled | bool
