---
- name: restart service
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
  when: elasticsearch_is_installed.rc != 0

- name: manual restart message
  ansible.builtin.debug:
    msg:
      - "****"
      - "**** !!! MANUAL RESTART NEEDED !!!"
      - "**** Configuration files changed, you have to restart elasticsearch manually"
      - "****"
  when: elasticsearch_is_installed.rc == 0
